language: python
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements-dev.txt
  - python setup.py sdist bdist_wheel
  - pip install dist/*.whl
  - ./build_tests.py
script:
  - py.test
